### PR TITLE
Database plugin

### PR DESCRIPTION
**Pull request by gurbir-a**
Dumps and update data in database from rawdog

### CODE REVIEW

**Comment by ranveeraggarwal** [comment]
Can you explain what I need to do to make this work?
As in, what users I need to create and whether or not I need to have a database ready?

Put all this in the README.

**Comment by ranveeraggarwal** [comment]
Also, fix your error messages. 

```
psycopg2.ProgrammingError
```

gives a lot more information than you're displaying (permissions issue, etc)

**Comment by gurbir-a** [comment]
I'll add these instructions in README

**Comment by gurbir-a** [comment]
Can you elaborate on the fix about error messages? Shall I print the full `psycopg2.ProgrammingError`?

**Comment by ranveeraggarwal** [comment]
Yeah, it's better if you output complete errors. It'll be easier to debug installations in that case.

**Comment by gurbir-a** [comment]
Done with the changes you mentioned.

**Comment by ranveeraggarwal** [comment]
Looks good to me. One last thing. What is that `out` file in the commit?

**Comment by gurbir-a** [comment]
Sample data (format) of article object from rawdog.

**Comment by ranveeraggarwal** [comment]
Remove that if not required. I'll do a final check and then I guess we can
go ahead with the merge.

**Pull request merged**
